
GET http://localhost:5000

###

POST http://localhost:5001/login
Content-Type: application/json

{
    "username" : "john"
}
###

GET http://localhost:5000/getusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2Njg4NDU5MDAsImV4cCI6MTY2ODg0NjAyMH0.XT6I64THtSVvbR0R0ioPifDb7Zzddv9aQzCjosUnswA


###
POST http://localhost:5001/refreshToken
Content-Type: application/json

{
    "name" : "vikram",
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa3JhbSIsImlhdCI6MTY2ODc3MTgyMSwiZXhwIjoxNjY4NzcyMDYxfQ.lt2hNT_F4Uxx2efiT3z4ewQWPGmznO4RKu0MlsxiDy0"
}

###
POST http://localhost:5001/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpa3JhbSIsImlhdCI6MTY2ODY5MDU4NSwiZXhwIjoxNjY4NjkwODI1fQ.Y6XmGmv2aySeeLZKYrRUMfwqnAsKpz1yzoPxt7i638A"
}

